<!DOCTYPE html>
<html lang="en" style="height: 100%;">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    
    <!-- 添加有关网页的描述信息 -->
    <meta name="description" content="YUOS 114514 Web Version - 一个开放源项目，提供对 YUOS 114514 的网络预览。">

	<!-- YUOS 114514 yumiqiye  -->

	<!-- YUOS 114514 网页版是一个开放源项目,
	希望让用户在网络上预先体验 YUOS 114514,
	内容可能与 YUOS 114514 正式版本不一致。
	使用标准网络技术,例如 HTML、CSS 和 Javascript
	此项目绝不附属于微软,且不应与微软操作系统或产品混淆,
	这也不是 Windows365 cloud PC
	本项目中微软、Windows和其他示范产品是微软公司的商标 -->
	<link rel="stylesheet" href="./base.css" />
	<base target="_blank">

	<title>YUOS 114514</title>
</head>
<body>
    <style>
	*{
	    cursor:none !important;
	}
        body{
            width: 100%;
            height: 100%;
            background-color: #005eaa;
            cursor: none;
        }
        #box{
            display: flex;
            flex-direction: column;
            justify-items: center;
            width: 70%;
            left: 15%;
            position: absolute;
            height: 100%;
            justify-content: center;
        }
        #happy-face{
            color: #fff;
            font-size: 150px;
            margin: 0;
            line-height: 1;
            /* margin-left: -40px; */
            margin-top: -10px;
            height: 150px;
            height: 150px;
            display: flex;
        }
        #happy-face>*{
            position: relative;
            line-height: 0px;
        }
        @keyframes eyea{
            0%{
                top: -140px;
                left: -40px;
            }
            15%{
                top: -150px;
                left: -60px;
            }
            25%{
                top: -140px;
                left: -40px;
            }
            35%{
                top: -150px;
                left: -20px;
            }
            50%{
                top: -140px;
                left: -40px;
            }
            85%{
                top: -140px;
                left: -40px;
            }
            95%{
                top: -45px;
                left: -40px;
            }
            /* 63%{
                top: 0px;
                left: 0;
            } */
        }
        #happy-face>.eye.a{
            top: -45px;
            left: -40px;
            animation: eyea 2s;
        }
        @keyframes eyeb{
            0%{
                top: -140px;
                left: 14px;
            }
            15%{
                top: -150px;
                left: -6px;
            }
            25%{
                top: -140px;
                left: 14px;
            }
            35%{
                top: -150px;
                left: 34px;
            }
            50%{
                top: -140px;
                left: 24px;
            }
            90%{
                top: -140px;
                left: 24px;
            }
        }
        #happy-face>.eye.b{
            left: -76px;
            top: -125px;
            animation: eyeb 2s;
        }
        @keyframes mou{
            0%{
                transform: rotate(90deg);
                top: 10px;
                left: -60px;
            }
            15%{
                transform: rotate(120deg);
                top: -10px;
                left: -80px;
            }
            25%{
                transform: rotate(90deg);
                top: 10px;
                left: -60px;
            }
            35%{
                transform: rotate(60deg);
                top: -10px;
                left: -20px;
            }
            50%{
                transform: rotate(270deg);
                top: 10px;
                left: -80px;
            }
            80%{
                transform: rotate(270deg);
                top: -10px;
                left: -80px;
            }
            90%{
                transform: rotate(180deg);
                top: -25px;
                left: -60px;
            }
            /* 50%{
                transform: rotate(180deg);
                top: 20px;
                left: 50px;
            } */
        }
        #happy-face>.mouse{
            transform: rotate(180deg);
            top: -25px;
            left: -60px;
            animation: mou 2s;
        }
        #tx1{
            color: #fff;
            font-size: 23px;
            margin-bottom: 5px;
            margin-top: 50px;
        }
        #prog{
            color: #fff;
            font-size: 23px;
        }
        #dtx{
            color: #fff;
            margin-left: 20px;
            font-size: 17px;
            margin-top: 0;
        }
        #qr{
            min-width: 150px;
            width: 150px;
            height: 150px;
            fill: #005eaa;
            background-color: #fff;
        }
        #detail{
            display: flex;
        }
        .link{
            color: #efefef;
            text-decoration: none;
            transition: 100ms;
            cursor: pointer;
        }
        .link:hover{
            color: #aaa;
        }
    </style>
    <div id="box">
        <div id="happy-face">
            <p class="eye a">.</p>
            <p class="eye b">.</p>
            <p class="mouse">)</p>
        </div>
        <p id="tx1">你的设备遇到问题，需要重启。<br>我们只假装收集某些错误信息，然后为你重新蓝屏。</p>
        <p id="prog"><span id="complete">0</span>% 完成</p>
        <div id="detail">
      <img border="0" src="qrcode.png" alt="Pulpit rock" width="150" height="150">
     <p id="dtx">有关此问题的详细信息和可能的解决方案，请访问<br><a onclick="window.open('https://space.bilibili.com/3546648932256226','_blank')" class="link">https://www.github.com/yumiqiye</a><br><br>如果致电支持人员，请向他们提供以下信息：<br>终止代码: <span id="stopcode">YUOS 114514 WAS NOT Normal Operation</span></p>
        </div>
    </div>
    <script src="scripts/jq.min.js"></script>
    <script>
        function sleep(millisecond, callback) {
            // 延迟指定的毫秒数后执行回调函数
            setTimeout(callback, millisecond);
        }

        function update_complete() {
            // 更新complete元素的文本内容，将其值加1
            complete.innerText = (parseInt(complete.innerText) + 1).toString();
        }
        function next_loop(element) {
            // 将complete元素的文本内容解析为整数
            var i = parseInt(complete.innerText, 10);
            // 定义延迟时间数组
            var delays = [300, 200, 100, 50];

            if (i >= 100) {
                 // 重新加载页面
                reload();
                return;
            }

            var delay;
            if (i < 20) {
                // 对应i小于20时的延迟时间
                delay = delays[0];
            } else if (i < 60) {
                // 对应i小于60时的延迟时间
                delay = delays[1];
            } else if (i < 80) {
                 // 对应i小于80时的延迟时间
                delay = delays[2];
            } else {
                // 对应i大于等于80时的延迟时间
                delay = delays[3];
            }

            sleep(delay, function () {
                 // 更新complete元素的值
                update_complete();
                 // 递归调用next_loop函数，形成循环
                next_loop();
            });
        }

        function reload() {
            // 重新加载页面
            window.location.reload();
        }

        let complete = document.getElementById("complete");
        next_loop();
        // 从URL参数中获取名为"code"的值
        var r = window.location.search.substr(1).match(/(^|&)code=([^&]*)(&|$)/);
        if(r!=null){
            document.getElementById('stopcode').innerHTML = r[2];
        }
    </script>
</body>
</html>
